#### Easy admin bundle
easy_admin:
    site_name: 'podelis-admin'
    design:
        brand_color: '#389222'
        assets:
#   TODO:         favicon: '/assets/backend/favicon.png'
        menu:
            - label: 'Question Reports'
              children: ['Report', 'Deniend']
            - label: 'Questions'
              children: ['Question', 'Added', 'Deniend_Questions', 'Reported']
            - label: 'Users'
              children: ['User', 'Disabled', 'Admin']
            - label: 'Answer'
              entity: 'Answer'
    entities:

    # Question reports menu items
        Report:
            class:  AppBundle\Entity\QuestionReport
            label: 'Submitted Reports'
            list:
                title: 'Submitted question reports'
                fields: ['id', 'question', 'created_by', 'updated_at', 'status']
                dql_filter: 'entity.status = 1'
            new:
                fields:
                    - reason
            edit:
                fields:
                    - question
                    - reason
                    - created_by
                    - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Approved': 'Approved', 'Denied': 'Denied' } } }
#        Approved:
#            disabled_actions: ['new']
#            class:  AppBundle\Entity\QuestionReport
#            label: 'Approved Reports'
#            list:
#                title: 'Approved question reports'
#                fields: ['id', 'question', 'created_by', 'updated_at', 'status']
#                dql_filter: 'entity.status = 2'
#            edit:
#                title: 'Edit report'
#                fields:
#                    - question
#                    - reason
#                    - created_by
#                    - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Approved': 'Approved', 'Denied': 'Denied' } } }
        Deniend:
            disabled_actions: ['new']
            class:  AppBundle\Entity\QuestionReport
            label: 'Deniend Reports'
            list:
                title: 'Deniend question reports'
                fields: ['id', 'question', 'created_by', 'updated_at', 'status']
                dql_filter: 'entity.status = 3'
            edit:
                title: 'Edit report'
                fields:
                    - question
                    - reason
                    - created_by
                    - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Approved': 'Approved', 'Denied': 'Denied' } } }

# Question and question suggestions menu
        Question:
            class: AppBundle\Entity\Question
            label: 'New Question requests'
            list:
                title: 'User suggested questions'
                fields: ['id', 'book', 'title', 'created_by', 'reports', 'updated_at', 'status']
                dql_filter: 'entity.status = 1'
            new:
                fields:
                    - book
                    - title
                    - content
                    - explanation
                    - answers
            edit:
                fields:
                    - book
                    - title
                    - content
                    - explanation
                    - answers
                    - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Added': 'Added', 'Denied': 'Denied' } } }
        Added:
             disabled_actions: ['new']
             class: AppBundle\Entity\Question
             label: 'Added Questions'
             list:
                 title: 'Added questions'
                 fields: ['id', 'book', 'title', 'created_by', 'reports', 'updated_at', 'status']
                 dql_filter: 'entity.status = 2'
             edit:
                 title: 'Edit question'
                 fields:
                     - book
                     - title
                     - content
                     - explanation
                     - answers
                     - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Added': 'Added', 'Denied': 'Denied' } } }

        Deniend_Questions:
            disabled_actions: ['new']
            class: AppBundle\Entity\Question
            label: 'Deniend Questions'
            list:
                title: 'Deniend questions'
                fields: ['id', 'book', 'title', 'created_by', 'reports', 'updated_at', 'status']
                dql_filter: 'entity.status = 3'
#                sort: 'reports'
            edit:
                title: 'Edit question'
                fields:
                    - book
                    - title
                    - content
                    - explanation
                    - answers
                    - { property: 'status', type: 'choice', type_options: { multiple: false, choices: { 'Submitted': 'Submitted', 'Added': 'Added', 'Denied': 'Denied' } } }
        Reported:
            disabled_actions: ['new']
            class: AppBundle\Entity\Question
            label: 'Reported questions'
            list:
                title: 'Reported Questions'
                fields: ['id', 'book', 'title', 'created_by', 'reports', 'updated_at', 'status']
#      TODO: filter by reports          dql_filter: ''
            edit:
                title: 'Edit question'
                fields:
                    - book
                    - title
                    - content
                    - explanation
                    - answers
                    - status
# User menu
        User:
            class: AppBundle\Entity\User
            label: 'Active Users'
            disabled_actions: ['delete']
            list:
                title: 'Active users'
                fields:
                    - 'id'
                    - { property: 'avatar', type: 'image' }
                    - 'username'
                    - 'email'
                    - 'enabled'
                    - 'roles'
                dql_filter: "entity.roles NOT LIKE '%%ROLE_ADMIN%%' AND entity.enabled = true"
            edit:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - enabled
        Admin:
            class: AppBundle\Entity\User
            label: 'Administrators'
            disabled_actions: ['delete']
            list:
                title: 'Administrators'
                fields:
                    - 'id'
                    - { property: 'avatar', type: 'image' }
                    - 'username'
                    - 'email'
                    - 'enabled'
                dql_filter: "entity.roles LIKE '%%ROLE_ADMIN%%' AND entity.enabled = true"
            edit:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - enabled
        Disabled:
            disabled_actions: ['new', 'delete']
            class: AppBundle\Entity\User
            label: 'Disabled Users'
            list:
                title: 'Disabled users'
                fields:
                    - 'id'
                    - { property: 'avatar', type: 'image' }
                    - 'username'
                    - 'email'
                    - 'enabled'
                    - 'roles'
                dql_filter: 'entity.enabled = false'
            edit:
                title: 'Edit user'
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - enabled
# answer section
        Answer:
            class: AppBundle\Entity\Answer
            label: 'Answers'
            list:
                title: 'Answers'
                fields:
                    - 'id'
                    - 'question'
                    - 'correct'
                    - 'updated at'
            edit:
                fields:
#                    - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - correct
                    - question
                    - content
