# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.send_email:
        class: AppBundle\Service\EmailSender
        arguments: ["@mailer", "@templating"]

    app.test_control:
        class: AppBundle\Service\TestControl
        arguments: ["@session", "@security.token_storage", "@doctrine.orm.entity_manager"]

    app.test_question:
        class: AppBundle\Form\TestQuestionType
        arguments: ["@app.test_control"]
        tags:
            - { name: form.type }

    app.test_starter:
        class: AppBundle\Service\TestStarter
        arguments: ["@session"]

    my_user_provider:
        class: AppBundle\Service\FOSUBUserProvider
        arguments: ["@fos_user.user_manager", {facebook: facebook_id, google: google_id}]

#    app.form.registration:
#        class: AppBundle\Form\UserType
#        tags:
#            - { name: form.type, alias: app_user_registration }

#    app.user.redirect.listener:
#        class: AppBundle\EventListener\RedirectUserListener
#        arguments: ["@security.token_storage", "@router"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.contribution.listener:
        class: AppBundle\EventListener\NotificationListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
